version: '3.8'

services:
   core:
     image: public.ecr.aws/classic-terra/core:alpine3.17
     build:
      context: ../..
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
      labels:
        - "description=Contains the terrad binary"
   node:
     image: public.ecr.aws/classic-terra/node:alpine3.17
     build: 
      context: .
      dockerfile: Dockerfile
      args:
        base_image: public.ecr.aws/classic-terra/core
        version: alpine3.17
      platforms:
        - "linux/amd64"
      labels:
        - "description=Contains everything to run a full node"