coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: 
      default:
        threshold: 1% # allow this much decrease on project
    changes: false

comment:
  layout: "reach, diff, files"
  behavior: default  # update if exists else create new

ignore:
  - "*.md"
  - "*.rst"
  - "cmd/"
  - "contrib/"
  - "docs/"
  - "networks/"
  - "**/cli"
  - "**/rest"
