project_name: terra

before:
  hooks:
    - make tools
    - make go-mod-cache

builds:
  -
    id: 'terracli'
    main: cmd/terracli/main.go
    binary: terracli
    flags:
      - -tags=netgo
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -X github.com/cosmos/cosmos-sdk/version.Name=terra 
      -X github.com/cosmos/cosmos-sdk/version.ServerName=terrad 
      -X github.com/cosmos/cosmos-sdk/version.ClientName=terracli 
      -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    id: 'terrad'
    main: ./cmd/terrad
    binary: terrad
    flags:
      - -tags=netgo
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -X github.com/cosmos/cosmos-sdk/version.Name=terra 
      -X github.com/cosmos/cosmos-sdk/version.ServerName=terrad 
      -X github.com/cosmos/cosmos-sdk/version.ClientName=terracli 
      -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
