project_name: terra

before:
  hooks:
    - make get_tools
    - make go-mod-cache

builds:
  -
    id: 'terracli'
    main: ./cmd/terracli/main.go
    binary: terracli
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w
      -X github.com/terra-project/core/version.Version={{.Version}}
      -X github.com/terra-project/core/version.Commit={{.Commit}}
      -X "github.com/terra-project/core/version.BuildTags={{.Env.BUILD_TAGS}}"
      -X github.com/terra-project/core/version.GoSumHash={{.Env.GOSUM}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    id: 'terrad'
    main: ./cmd/terrad/main.go
    binary: terrad
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w
      -X github.com/terra-project/core/version.Version={{.Version}}
      -X github.com/terra-project/core/version.Commit={{.Commit}}
      -X "github.com/terra-project/core/version.BuildTags={{.Env.BUILD_TAGS}}"
      -X github.com/terra-project/core/version.GoSumHash={{.Env.GOSUM}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

  -
    id: 'terrakeyutil'
    main: ./cmd/terrakeyutil/main.go
    binary: terrakeytutil
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w
      -X github.com/terra-project/core/version.Version={{.Version}}
      -X github.com/terra-project/core/version.Commit={{.Commit}}
      -X "github.com/terra-project/core/version.BuildTags={{.Env.BUILD_TAGS}}"
      -X github.com/terra-project/core/version.GoSumHash={{.Env.GOSUM}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
