// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-money/core/x/bank/internal/types/
package bank

import (
	"github.com/terra-money/core/x/bank/internal/types"
)

var (
	// functions aliases
	RegisterCodec = types.RegisterCodec

	// variable aliases
	ModuleCdc      = types.ModuleCdc
	BurnModuleName = types.BurnModuleName
)
