// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-money/core/x/genutil/internal/types/
package genutil

import (
	"github.com/terra-money/core/x/genutil/internal/types"
)

var (
	ModuleCdc = types.ModuleCdc
)

type (
	StakingKeeper           = types.StakingKeeper
	AccountKeeper           = types.AccountKeeper
	GenesisAccountsIterator = types.GenesisAccountsIterator
)
