package app

const (
	appName     = "TerraApp"
	upgradeName = "columbus-6"

	authzMsgExec                          = "/cosmos.authz.v1beta1.MsgExec"
	authzMsgGrant                         = "/cosmos.authz.v1beta1.MsgGrant"
	authzMsgRevoke                        = "/cosmos.authz.v1beta1.MsgRevoke"
	bankMsgSend                           = "/cosmos.bank.v1beta1.MsgSend"
	bankMsgMultiSend                      = "/cosmos.bank.v1beta1.MsgMultiSend"
	distrMsgSetWithdrawAddr               = "/cosmos.distribution.v1beta1.MsgSetWithdrawAddress"
	distrMsgWithdrawValidatorCommission   = "/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"
	distrMsgFundCommunityPool             = "/cosmos.distribution.v1beta1.MsgFundCommunityPool"
	distrMsgWithdrawDelegatorReward       = "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"
	feegrantMsgGrantAllowance             = "/cosmos.feegrant.v1beta1.MsgGrantAllowance"
	feegrantMsgRevokeAllowance            = "/cosmos.feegrant.v1beta1.MsgRevokeAllowance"
	govMsgVoteWeighted                    = "/cosmos.gov.v1beta1.MsgVoteWeighted"
	govMsgSubmitProposal                  = "/cosmos.gov.v1beta1.MsgSubmitProposal"
	govMsgDeposit                         = "/cosmos.gov.v1beta1.MsgDeposit"
	govMsgVote                            = "/cosmos.gov.v1beta1.MsgVote"
	stakingMsgEditValidator               = "/cosmos.staking.v1beta1.MsgEditValidator"
	stakingMsgDelegate                    = "/cosmos.staking.v1beta1.MsgDelegate"
	stakingMsgUndelegate                  = "/cosmos.staking.v1beta1.MsgUndelegate"
	stakingMsgBeginRedelegate             = "/cosmos.staking.v1beta1.MsgBeginRedelegate"
	stakingMsgCreateValidator             = "/cosmos.staking.v1beta1.MsgCreateValidator"
	vestingMsgCreateVestingAccount        = "/cosmos.vesting.v1beta1.MsgCreateVestingAccount"
	transferMsgTransfer                   = "/ibc.applications.transfer.v1.MsgTransfer"
	marketMsgSwapMsg                      = "/terra.market.v1beta1.MsgSwap"
	marketMsgSwapSendMsg                  = "/terra.market.v1beta1.MsgSwapSend"
	oracleMsgAggregateExchangeRatePrevote = "/terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote"
	oracleMsgAggregateExchangeRateVote    = "/terra.oracle.v1beta1.MsgAggregateExchangeRateVote"
	oracleMsgDelegateFeedConsent          = "/terra.oracle.v1beta1.MsgDelegateFeedConsent"
	wasmMsgStoreCode                      = "/terra.wasm.v1beta1.MsgStoreCode"
	wasmMsgExecuteContract                = "/terra.wasm.v1beta1.MsgExecuteContract"
	wasmMsgInstantiateContract            = "/terra.wasm.v1beta1.MsgInstantiateContract"
	wasmMsgMigrateContract                = "/terra.wasm.v1beta1.MsgMigrateContract"
)
