// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-project/core/x/treasury/internal/types/
// ALIASGEN: github.com/terra-project/core/x/treasury/internal/keeper/
package treasury

import (
	"github.com/terra-project/core/x/treasury/internal/keeper"
	"github.com/terra-project/core/x/treasury/internal/types"
)

const (
	DefaultCodespace               = types.DefaultCodespace
	CodeInvalidEpoch               = types.CodeInvalidEpoch
	ModuleName                     = types.ModuleName
	StoreKey                       = types.StoreKey
	RouterKey                      = types.RouterKey
	QuerierRoute                   = types.QuerierRoute
	DefaultParamspace              = types.DefaultParamspace
	ProposalTypeTaxRateUpdate      = types.ProposalTypeTaxRateUpdate
	ProposalTypeRewardWeightUpdate = types.ProposalTypeRewardWeightUpdate
	QueryTaxRate                   = types.QueryTaxRate
	QueryTaxCap                    = types.QueryTaxCap
	QueryRewardWeight              = types.QueryRewardWeight
	QuerySeigniorageProceeds       = types.QuerySeigniorageProceeds
	QueryTaxProceeds               = types.QueryTaxProceeds
	QueryParameters                = types.QueryParameters
)

var (
	// functions aliases
	RegisterCodec                 = types.RegisterCodec
	ErrInvalidEpoch               = types.ErrInvalidEpoch
	NewGenesisState               = types.NewGenesisState
	DefaultGenesisState           = types.DefaultGenesisState
	ValidateGenesis               = types.ValidateGenesis
	GetTaxCapKey                  = types.GetTaxCapKey
	GetTRKey                      = types.GetTRKey
	GetSRKey                      = types.GetSRKey
	GetTSLKey                     = types.GetTSLKey
	GetSubkeyByEpoch              = types.GetSubkeyByEpoch
	DefaultParams                 = types.DefaultParams
	NewTaxRateUpdateProposal      = types.NewTaxRateUpdateProposal
	NewRewardWeightUpdateProposal = types.NewRewardWeightUpdateProposal
	NewQueryTaxCapParams          = types.NewQueryTaxCapParams
	TRL                           = keeper.TRL
	SR                            = keeper.SR
	MR                            = keeper.MR
	NewKeeper                     = keeper.NewKeeper
	ParamKeyTable                 = keeper.ParamKeyTable
	NewQuerier                    = keeper.NewQuerier

	// variable aliases
	ModuleCdc                            = types.ModuleCdc
	TaxRateKey                           = types.TaxRateKey
	RewardWeightKey                      = types.RewardWeightKey
	TaxCapKey                            = types.TaxCapKey
	TaxProceedsKey                       = types.TaxProceedsKey
	EpochInitialIssuanceKey              = types.EpochInitialIssuanceKey
	CumulatedHeightKey                   = types.CumulatedHeightKey
	TRKey                                = types.TRKey
	SRKey                                = types.SRKey
	TSLKey                               = types.TSLKey
	ParamStoreKeyTaxPolicy               = types.ParamStoreKeyTaxPolicy
	ParamStoreKeyRewardPolicy            = types.ParamStoreKeyRewardPolicy
	ParamStoreKeySeigniorageBurdenTarget = types.ParamStoreKeySeigniorageBurdenTarget
	ParamStoreKeyMiningIncrement         = types.ParamStoreKeyMiningIncrement
	ParamStoreKeyWindowShort             = types.ParamStoreKeyWindowShort
	ParamStoreKeyWindowLong              = types.ParamStoreKeyWindowLong
	ParamStoreKeyWindowProbation         = types.ParamStoreKeyWindowProbation
	DefaultTaxPolicy                     = types.DefaultTaxPolicy
	DefaultRewardPolicy                  = types.DefaultRewardPolicy
	DefaultSeigniorageBurdenTarget       = types.DefaultSeigniorageBurdenTarget
	DefaultMiningIncrement               = types.DefaultMiningIncrement
	DefaultWindowShort                   = types.DefaultWindowShort
	DefaultWindowLong                    = types.DefaultWindowLong
	DefaultWindowProbation               = types.DefaultWindowProbation
	DefaultTaxRate                       = types.DefaultTaxRate
	DefaultRewardWeight                  = types.DefaultRewardWeight
)

type (
	PolicyConstraints          = types.PolicyConstraints
	SupplyKeeper               = types.SupplyKeeper
	MarketKeeper               = types.MarketKeeper
	StakingKeeper              = types.StakingKeeper
	DistributionKeeper         = types.DistributionKeeper
	GenesisState               = types.GenesisState
	Params                     = types.Params
	TaxRateUpdateProposal      = types.TaxRateUpdateProposal
	RewardWeightUpdateProposal = types.RewardWeightUpdateProposal
	QueryTaxCapParams          = types.QueryTaxCapParams
	Keeper                     = keeper.Keeper
)
