// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-project/core/x/distribution/internal/types/
package distribution

import (
	"github.com/terra-project/core/x/distribution/internal/types"
)

var (
	// functions aliases
	RegisterCodec = types.RegisterCodec

	// variable aliases
	ModuleCdc = types.ModuleCdc
)
