// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-money/core/x/crisis/internal/types/
package gov

import (
	"github.com/terra-money/core/x/gov/internal/types"
)

var (
	// functions aliases
	RegisterCodec             = types.RegisterCodec
	RegisterProposalTypeCodec = types.RegisterProposalTypeCodec

	// variable aliases
	ModuleCdc = types.ModuleCdc
)
